name: Build Mod

on: [push, pull_request, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build mod jar
      run: |
        chmod +x ./gradlew
        ./gradlew deploy
    - name: Get mod version
      id: version
      run: echo "mod_version=$(grep '^version:' mod.hjson | cut -d':' -f2 | tr -d ' ')" >> $GITHUB_OUTPUT
    - name: Upload built jar file
      uses: actions/upload-artifact@v4
      with:
        name: silicon-${{ steps.version.outputs.mod_version }}-v159.7
        path: build/libs/silicon-${{ steps.version.outputs.mod_version }}-v159.7.jar
